auth:
  local:
    jwt-access-secret: ${JWT_ACCESS_SECRET}
    jwt-refresh-secret: ${JWT_REFRESH_SECRET}
    jwt-access-life-duration: ${JWT_ACCESS_DURATION}
    jwt-refresh-life-duration: ${JWT_REFRESH_DURATION}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: method

server:
  port: ${PORT:8080}